version: '2'
services:
  service: # Main
    build:
      context: .
      dockerfile: buildsystem/Dockerfile
    environment:
      NODE_ENV: 'development'
      APP_LOG: '/var/log/app.log'
      API_PORT: 9000
    volumes:
      - ./src:/home/node/app/src
      - ./scripts:/home/node/app/scripts
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 9000:9000
      - 9222:9222
      - 3000:3000
